### ISSUE TITLE
How to enable?

### ISSUE THREAD

**Issue by BrunoKrugel** [coderosh/vscode-swaggo-highlight-snippets#1]
My comments are not being highlighted.

How to enable or troubleshoot the extension not working?

**Comment by coderosh** [comment]
Should work by default.
Can you provide me with the code that didn't work?

**Comment by BrunoKrugel** [comment]
The first time I open the code it has highlight, then its overriden, after a few seconds
```
// TestHandler godoc
//
//	@Summary		lorem ipsum
//	@Description	        lorem ipsum
//	@Tags			lorem ipsum
//	@accepts		json
//	@produces		json
//	@Success		200
//	@Router			/lorem/ipsum [GET]
```

![image](https://github.com/user-attachments/assets/c8029060-60b0-46d1-81b7-3000175da737)

**Comment by coderosh** [comment]
Looks like turning gopls `ui.semanticTokens` on overrides the colors added by this extension.

**Comment by BrunoKrugel** [comment]
Yep, you are right, maybe add this in the readme to help future users?

Great plugin btw
